name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      api:
        image: farimalik265/todoapi-repository
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v4

      # 1️⃣ Install .NET 9.0.12 explicitly (not using setup-dotnet)
      - name: Install .NET 8 SDK
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x ./dotnet-install.sh
          ./dotnet-install.sh --version 9.0.12 --install-dir /usr/share/dotnet
          sudo ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

      # 2️⃣ Verify installation
      - name: Check .NET version
        run: |
          dotnet --list-sdks
          dotnet --version

      # 3️⃣ Restore & Build
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal