name: .NET CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      api:
        image: farimalik265/todoapi-repository
        ports:
          - 8080:8080

    steps:
      - uses: actions/checkout@v4

      # 1. FIRST Install required system dependencies
      - name: Install prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y wget

      # 2. PROPERLY Install .NET 8 SDK (direct from Microsoft)
      - name: Install .NET 8 SDK
        run: |
          wget https://dot.net/v1/dotnet-install.sh -O dotnet-install.sh
          chmod +x ./dotnet-install.sh
          ./dotnet-install.sh --version 8.0.301 --install-dir /usr/share/dotnet
          sudo ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

      # 3. VERIFY Installation
      - name: Check .NET version
        run: |
          dotnet --list-sdks
          dotnet --version

      # Rest of your workflow...
      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-build --verbosity normal